spring.application.name=Suscripciones
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/suscripciones
spring.datasource.username=admin
spring.datasource.password=suscripciones123
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.rabbitmq.exchange.pagos=pagos-exchange

app.rabbitmq.exchange.suscripcion=suscripcion-exchange

app.rabbitmq.queue.exitoso=pago-exitoso-queue
app.rabbitmq.routing-key.exitoso=pago-exitoso

app.rabbitmq.queue.fallido=pago-fallido-queue
app.rabbitme.routing-key.fallido=pago-fallido

app.rabbitmq.queue.suscripcion-creada=suscripcion-creada-queue
app.rabbitmq.routing-key.suscripcion-creada=suscripcion-creada

springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.try-it-out-enabled=true

