spring.application.name=Pagos
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/pagos
spring.datasource.username=admin
spring.datasource.password=suscripciones123
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

app.rabbitmq.exchange.pagos=pagos-exchange

app.rabbitmq.exchange.suscripcion=suscripcion-exchange

app.rabbitmq.queue.exitoso=pago-exitoso-queue
app.rabbitmq.routing-key.exitoso=pago-exitoso

app.rabbitmq.queue.fallido=pago-fallido-queue
app.rabbitmq.routing-key.fallido=pago-fallido

app.rabbitmq.queue.notificacion=notificacion-queue
app.rabbitmq.queue.suscripcion-creada=suscripcion-creada-queue
app.rabbitmq.routing-key.suscripcion-creada=suscripcion-creada
