spring.application.name=Usuario
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/usuarios
spring.datasource.username=admin
spring.datasource.password=suscripciones123
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
